apiVersion: v1
kind: Pod
metadata:
  name: multipod
spec:
  nodeSelector: 
    PURPOSE: DB
  containers: 
    - name: centos
      image: centos
      command: ["sleep"]
      args: ["10000"]
    - name: mariadb
      image: mariadb
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"

